// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXT3btF0QlURKZVjWs1OUUaygvtUP09tw',
    appId: '1:1003973125982:web:bace4d1266aa032a8fd1cf',
    messagingSenderId: '1003973125982',
    projectId: 'first-firebase-project-88226',
    authDomain: 'first-firebase-project-88226.firebaseapp.com',
    storageBucket: 'first-firebase-project-88226.appspot.com',
    measurementId: 'G-9W8TFP3D61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT2ea1b13ogjzLE_u2XHFNtTgchvYToyk',
    appId: '1:1003973125982:android:12dd851abacb47818fd1cf',
    messagingSenderId: '1003973125982',
    projectId: 'first-firebase-project-88226',
    storageBucket: 'first-firebase-project-88226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvbKOOcvyhC22yyrYdrO3JbLJrJ5NB4w4',
    appId: '1:1003973125982:ios:44ebdacd0b4236ca8fd1cf',
    messagingSenderId: '1003973125982',
    projectId: 'first-firebase-project-88226',
    storageBucket: 'first-firebase-project-88226.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvbKOOcvyhC22yyrYdrO3JbLJrJ5NB4w4',
    appId: '1:1003973125982:ios:a7d02f4014c28e038fd1cf',
    messagingSenderId: '1003973125982',
    projectId: 'first-firebase-project-88226',
    storageBucket: 'first-firebase-project-88226.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
